version: "3.9"
services:
  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
      - POSTGRES_DB=library
    ports:
      - "5450:5432"
    volumes:
      - ./sql/postgresql.sql:/docker-entrypoint-initdb.d/postgresql.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy